apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: bibblebabl/auth
      context: .
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: apps/auth/Dockerfile
    - image: bibblebabl/client
      context: .
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
      docker:
        dockerfile: apps/client/Dockerfile
    - image: bibblebabl/tickets
      context: .
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: apps/tickets/Dockerfile
    - image: bibblebabl/orders
      context: .
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: apps/orders/Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
