apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-367523/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-367523
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
