import axios from 'axios'
import { NextPageContext } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

type User = {
  id: string
  email: string
}

export default function Home({ currentUser }: { currentUser: null | User }) {
  console.log(currentUser)
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

Home.getInitialProps = async (ctx: NextPageContext) => {
  // if (typeof window === 'undefined')
  try {
    const response = await axios({
      url: '/api/users/currentuser',
      method: 'GET',
      headers: ctx?.req?.headers?.cookie ? { cookie: ctx.req.headers.cookie } : undefined,
      withCredentials: true,
    })

    return {
      currentUser: response.data.currentUser,
    }
  } catch (error) {
    return {
      currentUser: null,
    }
  }
}
