import { NextPageContext } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

type User = {
  id: string
  email: string
}

const Home = ({ currentUser }: { currentUser: null | User }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {currentUser ? `User email: ${currentUser.email}` : `You are not signed in`}
        </h1>
      </main>
    </div>
  )
}

Home.getInitialProps = async (ctx: NextPageContext) => {
  console.log(ctx)
  return {}
}

export default Home
