import { NextPageContext } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { buildClient } from '../api/build-client'

type User = {
  id: string
  email: string
}

interface Ticket {
  title: string
  price: number
  userId: string
}

const Home = ({ currentUser, tickets }: { currentUser: null | User; tickets: Ticket[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Tickets</h1>
        <table>
          <thead className="table">
            <tr>
              <th>Title</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            {tickets.map((ticket) => (
              <tr key={ticket.title}>
                <td>{ticket.title}</td>
                <td>{ticket.price}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  )
}

Home.getInitialProps = async (ctx: NextPageContext) => {
  const client = buildClient(ctx)
  const { data } = await client.get('/api/tickets')

  return {
    tickets: data,
  }
}

export default Home
